### ISSUE TITLE
Netcat in image, for health check

### ISSUE THREAD

**Issue by schildbach** [isc-projects/bind9-docker#3]
It would be nice if `nc` would be contained in the docker image, so a health check can easily be configured.

For the record, in my `docker-compose.yml` I used:

```
  healthcheck:
    test: ["CMD-SHELL", "nc -z localhost 53 || exit 1"]
```

but since a few versions it fails because nc cannot be found any more. If you agree, I can probably provide a PR.

**Comment by oerdnj** [comment]
I am missing why the health check has to be done from inside of the docker image. I think it's better to keep the image lean and clean.
