### ISSUE TITLE
Update container versioning to follow Bind9 release version

### ISSUE THREAD

**Issue by smbambling** [isc-projects/bind9-docker#6]
Currently the containers are versioned with tags like 9.16, a suggestion would be to make these tags follow the Bind9 release version like 9.16.20. This helps to prevent unwanted / tested updates in environments

**Comment by oerdnj** [comment]
This would go against the goal to provide the latest available version. If you want more fine-grained control, you can always mirror the Dockerfile into your private Docker repository and merge the updates manually.

Also, it's not really possible to do this as the Ubuntu PPA that the Dockerfile uses don't keep older versions, so the Dockerfile would have to build the BIND 9 from the scratch.

**Comment by smbambling** [comment]
You can have multiple tags for containers, when they are created. You can always apply a tag of 9.16 for those that want to get the latest and greatest and another tag for example 9.16.19 or 9.16.20 for those that want to obtain a specific version.

Even with the PPA not keeping older versions of the PPA the container was still built with a specific version set in the variable  DEB_VERSION. Once a container is published it no longer need the source PPA it will just be stored in the Docker registry 

If possible it would be ideal to avoid managing the Dockerfile ourselves, but can do as as needed.
