### ISSUE TITLE
Documentation on source of truth for publish container images

### ISSUE THREAD

**Issue by smbambling** [isc-projects/bind9-docker#7]
The Docker Hub page points to this repo as the source, but I see there are other project for Docker under GitLab which are more 

https://gitlab.isc.org/isc-projects/bind9-docker
https://gitlab.isc.org/isc-projects/images

Which of these projects should be followed for published containers ?
How often are releases for the containers updated?  I see that as of the creation of this issue 9.16.20 is viable in the  Ubuntu PPA https://launchpad.net/~isc/+archive/ubuntu/bind

**Comment by oerdnj** [comment]
* https://gitlab.isc.org/isc-projects/bind9-docker
- This one is the authoritative, this is just a mirror

* https://gitlab.isc.org/isc-projects/images
- This one is unrelated to public Docker images

**Comment by smbambling** [comment]
Cool thanks for the quick responses on these issues!

**Comment by oerdnj** [comment]
> How often are releases for the containers updated?

FTR Docker has changed policies and they no longer allow Builds on "Free Team" plan, which I have just discovered. I have now upgraded the ISC account to use their Team plan.

Also I disabled the ability to outside collaborators to interact with this repository (so you can't comment back) and updated the description of the repository to point to the GitLab.
